UINT8_SCALE = 255.0
FLOAT_SCALE = 1.0 / UINT8_SCALE

ADJUSTMENT_SCALE = 100.0

DT_BLOCK_SIZE = 7

SC_PIXEL_RED_LOW_HUE = 10
SC_PIXEL_RED_HIGH_HUE = 200
SC_PIXEL_BRIGHT_VAL_THRESHOLD = 80
SC_PIXEL_SATURATION_THRESHOLD = 50
SC_PIXEL_RED_WEIGHT = 0.2
SC_PIXEL_BRIGHTNESS_WEIGHT = 0.7
SC_PIXEL_RADIUS_RANGE = 5, 11

RD_LABEL_RADIUS_RANGE = 0, 3
